### ISSUE TITLE
Support for {phoenix_live_view ~> "0.18"}?

### ISSUE THREAD

**Issue by benonymus** [pepsico-ecommerce/chore_runner#11]
Hey,

The dep seems great, but it uses and older live_view version.
Any chance to support newer versions?

I added `override: true` to my `phoenix_live_view` dep, which allows me to install chore_runner, but compilation fails.

```
warning: passing a string as a layout template in use options is deprecated, please pass an atom, such as :live instead of "live.html"
  (phoenix_live_view 0.18.3) 
```

Thanks

**Comment by cjfreeze** [comment]
We now support LiveView 0.18 as of v0.4.0
